name: Build & Push to Docker Hub

on:
  #push:
    #branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/devopsendproj
  SHA_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Node image ----
      - name: Build & Push Node
        uses: docker/build-push-action@v6
        with:
          context: ./DevOpsEndProj-main/node
          push: true
          tags: |
           ${{ env.IMAGE_NAME }}:node
            ${{ env.IMAGE_NAME }}:node-${{ env.SHA_TAG }}
            ${{ env.IMAGE_NAME }}:node-latest
            
      # ---- PHP image ----
      - name: Build & Push PHP
        uses: docker/build-push-action@v6
        with:
          context: ./DevOpsEndProj-main/php
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:php
            ${{ env.IMAGE_NAME }}:php-${{ env.SHA_TAG }}
            ${{ env.IMAGE_NAME }}:php-latest
